### ISSUE TITLE
database scan fails with error for every file

### ISSUE THREAD

**Issue by dkanada** [IrosTheBeggar/mStream#107]
I set up the server and the database scan throws the following error for every file.

>stdout: Warning: failed to parse file 'song.flac': strtok3_1.IgnoreType is not a constructor

Any clue what the issue is? There are no albums or artists shown through the web interface so I assume it isn't parsing the files properly.

**Comment by dkanada** [comment]
The web client can play the files from the file explorer but the android app responds with the following messages.

>Failed to decoded server response. WTF
>Cannot sync non-hashed files. For now...

**Comment by dkanada** [comment]
The plot thickens ... even though the android app responds with the error messages and doesn't play the files, if I click the play button it plays the song anyways. I am guessing that the app cannot download the file (which is the "sync" feature) but it can still stream the song directly. The song queue seems to work and the player is working extremely well despite the bugs, just need to figure out the metadata issues.

Do you still use mStream for your own library? I haven't used mStream until now in favor of emby, but emby has been giving me lots of grief lately. Would you be open to some pull requests for the UI or android app?

**Comment by IrosTheBeggar** [comment]
Hey sorry for the late response.  Works been keeping me busy lately.

So this is all due to how mStream handles the DB.  The File Explorer doesn't need to DB to work . The server just calls the OS and gets the files.  The android download feature uses the sha256 hash to prevent downloading duplicate files.  Since the server is failing to parse the files and adding them to the DB, the android app isn't getting the sha256 hash and it's failing.

Can you send me one of the failing files?  I'll see if there's a fix I can apply to prevent it.  Send them to paul.sori@gmal.com

And yea, I still use mStream for my own stuff.  I've been super busy working at a startup, so I haven't had the time to develop the android app.  I would really appreciate any pull requests

**Comment by dkanada** [comment]
Just sent a file, that explanation makes a lot of sense.

Is the android app storing the cached files in a single directory and naming them with the hash for comparisons, or does it work a different way? Does it cache album art in the same directory?

**Comment by IrosTheBeggar** [comment]
That's correct about how the android system does thing.  The app doesn't cache album art right now.  But the server caches album art on it's end in a similar method.

Ideally the android app would save files the reflect the file structure on the server side. I wrote it this way to prevent some common problems.  For example, saving every file as a sha256 prevents duplicates from being downloaded and ensures the app uses as little space as possible. 

I'm planning on expanding on the sync functions, like adding a function that will keep a directory and all sub directories in sync.  But before that I need to finish a few things on the server side

**Comment by IrosTheBeggar** [comment]
I updated the metadata parsing library, and the problem was fixed
