### ISSUE TITLE
Hash passwords

### ISSUE THREAD

**Issue by rubenwardy** [IrosTheBeggar/mStream#110]
It's good practice not to store passwords in plaintext even if you only have a minimal number of hard coded users. There are a number of existing libraries available for this - make sure you use a strong salted hash like bcrypt2

**Comment by IrosTheBeggar** [comment]
You are correct.  I've been meaning to get working on a config management tools to do this, but that project keeps getting pushed back

Right now passwords are salted and hashed on server bootup with the nodeJS crypto library.  I used bcrypt in the past, but I switched due to bcrypt causing problems with installations for some users.

**Comment by IrosTheBeggar** [comment]
The latest commit adds JSON configuration script that can be used to store hashed passwords.  To run it do the following:

```shell
# make a empty JSON file if none exists
mstream --init config.json

# add path
mstream -j config.json --addpath /path/to/library

# add user (a prompt will walk you through user setup)
mstream -j config.json --adduser
```

There's several new tools that can be used to edit the JSON file.  Each of these tools needs to used with the `-j <filepath>` flag in order to work.  If the '-j' flag is missing, these commands will be ignored and the server will boot up.

```
--addpath <folder>
--adduser
--editport
--makesecret
--addkey <ssl key>
--addcert <ssl cert>
```

The `--adduser` command will prompt you for a password, and then store the hashed password in the JSON config file
