### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by theof** [IrosTheBeggar/mStream#111]
Hi !
It has been a while since the last release. There have been several bug fixes as well as new features such as the auto-dj.

Would you consider tagging a new release soon ? This allows system-wide packaged mStream to be upgraded easily and cleanly.

**Comment by IrosTheBeggar** [comment]
mStream is deff overdue for a release.  My Windows Certs expired recently and I haven't done a release since.  Windows Certs are expensive so I've been taking my time getting new ones.

I'll order some new certs soon (and maybe some OSX certs as well) so I can start doing releases again.  In the meantime I'll release some unsigned versions.  These are the same, but the OS shows some warnings about unidentified software when installing

**Comment by IrosTheBeggar** [comment]
Sorry this took so long.  I really wanted to get the butterchurn visualizer into this release

https://github.com/IrosTheBeggar/mStream/releases/tag/v3.6.0
