### ISSUE TITLE
Feature Request: Audio mix (DJ option), fade in / fade out

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#118]
For seamless playback add support for fade in  fade out so that music can be played seamlessly 
ie. fadeout +20 seconds, fadein +20 seconds so that there is some 'mix' like a radio station ;)

**Comment by IrosTheBeggar** [comment]
I'm moving this to ticket https://github.com/IrosTheBeggar/mStream/issues/92, since it's the catchall ticket for webapp feature requests.

This feature requires some serious work, since it would require rewriting the audio code to switch from html5 to Web Audio, (or better yet using a hybrid approach)[https://developers.google.com/web/updates/2012/02/HTML5-audio-and-the-Web-Audio-API-are-BFFs].

**Comment by Faranuddin4** [comment]
any solution
