### ISSUE TITLE
Mobile Browser Bug (Firefox Mobile)

### ISSUE THREAD

**Issue by jugendhacker** [IrosTheBeggar/mStream#132]
Hello,
I think I expirienced a strange bug with the auto DJ feature in Firefox on my Android mobile. Not sure if this is a bug in Firefox or in mStream. When I start playing auto DJ it loads the acutal song and after that it tries to load the next Song and gets a 206 but after some while it finishes the load of the next song with just a few hundred kb not with the hole song. So when it tries to play this Song it gets stuck until I skip to the next song. I hope you can help me! If you want I can provide some more logs...

**Comment by IrosTheBeggar** [comment]
Interesting, I'll download Firefox for Android and test this.

**Comment by jugendhacker** [comment]
Just little tip: If you have firfox on the pc you can use the debug tools to see whats going on ob the mobile over the WebIDE

**Comment by jugendhacker** [comment]
Funn Fact if I disable the caching in the debugger for my phone it seems to work fine...

**Comment by IrosTheBeggar** [comment]
Mobile browsers sometimes have media queries tied to touch events.  The idea is to prevent videos/songs from auto playing on load, but has all sorts of side affects like this.

**Comment by jugendhacker** [comment]
I think it has more to do with a caching bug in the application or in firefox...

**Comment by jugendhacker** [comment]
Could you investigate on this bug?

**Comment by IrosTheBeggar** [comment]
Yea, after work today

**Comment by IrosTheBeggar** [comment]
There's deff some caching bug causing this.  Need to investigate further

**Comment by IrosTheBeggar** [comment]
I pushed a fix that fixes a caching bug.  I only tested it in desktop though.  Let me know if it fixes your mobile problem

**Comment by jugendhacker** [comment]
The Bug still exists...

**Comment by jugendhacker** [comment]
The Bug still exists...

**Comment by IrosTheBeggar** [comment]
Ok, looks like there the library Howler.js is having some issues with Firefox mobile.   Looking into that now

**Comment by jugendhacker** [comment]
Is there a workaround?

**Comment by IrosTheBeggar** [comment]
@jugendhacker 

Unforuntly not.  Streaming to mobile browsers comes with a number of pain points.  For example, you cannot go to the next song if the screen turns off.  And there's just no way around that. This is due to the fact mobile browsers have an additional set of rules for media streaming.  That's why this bug is present of Firefox mobile but not on Firefox desktop.  

Ideally there would be an app for Android/iOS.  There's a few options here:

## Build native apps 

This is incredibly time consuming but comes with the best results.  There's already a native mStream Android app in alpha, but it hasn't been worked on in a while.  I would need another dev to help me with this is to make it a realistic option

## Piggy back off of Subsonic Apps

With some code, mStream can emulate the Subsonic API, and we could use Subsonic Apps with mStream servers.  However we would lose support for some mStream features and would constantly have to test the latest versions of these apps for compatibility.

## Make a Cordova App

This would let us share the Web UI on mobile platforms.  However Cordova is a pain to debug and I couldn't guarantee this would fix all the issues. More research needs to be done first

**Comment by IrosTheBeggar** [comment]
I opened an issue on howler for events not firing on firefox mobile:

https://github.com/goldfire/howler.js/issues/1054

**Comment by jugendhacker** [comment]
Yes I like the idea with a mobile app, but at the moment it isn't rellay usable and I also know that developing a native android app is very time consuming and also much more complicated than it should... Sadly I don't rellay undestand the android ui thing so can't help here! Hope you could find a developer for the app

**Comment by IrosTheBeggar** [comment]
I just had an idea for a fourth option:

## Sync Only App

It might be worth building Apps that just sync files between the server and phone. We let the user choose whatever app they want for playing.  The app would have a file browser and some menus for automated syncing.  This way the user doesn't have to juggle multiple music playing apps, and it minimizes work needed for the mStream app

**Comment by jugendhacker** [comment]
Yeay I also had this Idea, would be cool for now, because not much to develope...

**Comment by IrosTheBeggar** [comment]
I'm closing this ticket since it's not an mstream bug but rather a browser/library bug.  With the release of the mobile apps there's no reason to stream in a mobile browser anymore
