### ISSUE TITLE
IRC channel?

### ISSUE THREAD

**Issue by MaxLeiter** [IrosTheBeggar/mStream#137]
is there an mstream IRC channel for development discussion?

**Comment by jugendhacker** [comment]
Or better a XMPP room?

**Comment by MaxLeiter** [comment]
I feel IRC is more popular than XMPP, especially with opensource software and communities

**Comment by jugendhacker** [comment]
IRC isn't a really modern protocol, because:
* It doesn't federate (I have to register a new account on every server)
* It is not made for instable mobile connections
* It has no file sharing option
* No message archivment, so when you are offline and go back online don't get messages for the time you where offline

Sorry for IRC rant, but it isn't a good solution anymore in 2018

**Comment by MaxLeiter** [comment]
While your points are all true, I don't think they're entirely valid today.

- Most likely, a channel for this project would exist on Freenode. Most opensource projects are on Freenode, and thus there's a bit of cross-over between github contributors and those registered on it. 
- A lot of this depends on your client and your setup. Using a bouncer or software like TheLounge nullifies this.
- Again, most clients have either built-in file sharing or plugins to implement it
- A chat shouldn't be used for discussions that need to be referenced constantly - use github issues for that. Active contributors/speakers will have a bouncer or persistent client, and users who are joining just to ask a question or make a comment have no need to see previous messages.

**Comment by ddevault** [comment]
Note that IRC is federated, but there are several discrete networks.

**Comment by jugendhacker** [comment]
> * A lot of this depends on your client and your setup. Using a bouncer or software like TheLounge nullifies this.

Bouncers are not really nice, because you need anyways a device that runs 24/7 or have to use a third party service

> * Again, most clients have either built-in file sharing or plugins to implement it

But then again, ou have a third party software

> Note that IRC is federated, but there are several discrete networks.

I didn't know this, but I see noone using this, so there must be a problem with this or so right?

And now from me:
I think if you ever to the same, because all other's do this, where is there any forward? There wouldn't be any change if you go through your life with this theorie...

**Comment by ddevault** [comment]
What's wrong with third-party software?

>I didn't know this, but I see noone using this, so there must be a problem with this or so right?

Just about every network uses this. One-server networks are uncommon.

>I think if you ever to the same, because all other's do this, where is there any forward? There wouldn't be any change if you go through your life with this theorie...

Well, IRC has a lot of users. If you want access to them, you need to use IRC. Besides that, IRC is a venerable protocol with loads of open source clients, servers, libraries, bots, and so on. It's not pretty or shiny and new, but it's comfortable to use with a good client. Don't chase after shiny things when something works well today. If you want to innovate with chat, you can, but why here? Why is mStream the hill you're going to die on?

**Comment by jugendhacker** [comment]
> What's wrong with third-party software?

It's not build into the protocol

> Just about every network uses this. One-server networks are uncommon.

In my understanding of federation, this isn't real federation, because I can't join for example a freenode room with a hackint account...

XMPP has also many users, lots of open source clients, many server software and bots... so this isn't a real argument for IRC. And XMPP is also not really new, but it's extensible and so really comfortable. IRC isn't comfortable there isn't a good way of using it on mobile without a bouncer that has to run anytime! I don't want to innovate, but it seems there is no official romm at the moment and so it's perfect to start with something else than IRC!

**Comment by ddevault** [comment]
>It's not build into the protocol

I asked what's *wrong* with third-party software. Why does it need to be built into the protocol?

>In my understanding of federation, this isn't real federation, because I can't join for example a freenode room with a hackint account...

Like I said: there are several independent networks of federated servers. You can't log into every *network* with one account but you can log into every *server* of a given network with one account. Or you don't have to log in at all, nearly all IRC servers & channels let you participate anonymously.

XMPP is not used for open source discussions. IRC is.

**Comment by jugendhacker** [comment]
But in XMPP I can join with a existing account from a other server and I can join with anonymous accounts!

And XMPP is used for open source discussions, might be not in your world, but I'm in serveral XMPP MUCs/rooms that are discussion rooms about open source software! Why it shouldn't be used for that?

**Comment by ddevault** [comment]
>But in XMPP I can join with a existing account from a other server and I can join with anonymous accounts!

Not on every XMPP server you can't.

>And XMPP is used for open source discussions, might be not in your world, but I'm in serveral XMPP MUCs/rooms that are discussion rooms about open source software! Why it shouldn't be used for that?

Several, eh? I'm in over a hundred freenode channels, more than 3/4 of which are the official on-topic IRC channel for their respective open source projects. Like it or not, IRC is where open source discussions happen. You can try to fight the trend but you'll just be dooming your XMPP chat to obscurity and making it harder for users to find you.

**Comment by jugendhacker** [comment]
I don't like such not open for new IRC Nerds that staied stuck in the last century like you, but let's wait what the autor would say...

**Comment by IrosTheBeggar** [comment]
I didn't realize people felt so passionately about chat software 🙄

@MaxLeiter 
I don't have an IRC channel setup.  Never really thought this project was popular enough to deserve one.

I've been using discord server with some other devs.  I setup my own mStream server on Discord, so we'll give that a shot.  They don't require users to create an account just to hop on the server for a while, so anyone can drop by and ask questions easily.  Just use this link:

https://discord.gg/QQZTdaK

I will be adding it to the readme and then closing this ticket.

**Comment by ddevault** [comment]
Please don't use discord (closed source software) as the primary mode of communication for an open source software project. You're just alienating your most passionate userbase.

**Comment by jugendhacker** [comment]
I also don't like to use a centralised properitan software...

**Comment by IrosTheBeggar** [comment]
@SirCmpwn @jugendhacker 

Glad I could get you both to agree on something

Discord is a stop gap measure for now.  Thanks to my job at a startup I'm on a serious time crunch these days, and I just don't have the time to maintain a server.  I've been keeping my eye on the Matrix project, and will try to set one up in the future.

I also chose Discord because it has a low barrier to entry.  Anyone can just click that link and start chatting.  Of all the chat clients I've used, Discord is the most user friendly for new users.

I'm also not opposed to an IRC channel.  I'll set one up this weekend.  There's no reason we can't have two chat options. 

Is that a compromise everyone can agree on?

**Comment by MaxLeiter** [comment]
That’s better but as you said, this isn’t a very popular project so I think two different chats is too many. You can easily have a user hop on with something like https://demo.thelounge.chat/?nick=mstream-user&channels=mstream

Alternatively, I’d be open to hosting an instance of The Lounge that could be under the mstream.com domain name.

**Comment by IrosTheBeggar** [comment]
@MaxLeiter 

That's a slick looking IRC client.  What has to be done to add a mstream domain to the lounge?

**Comment by MaxLeiter** [comment]
I’d host it on a VPS and you’d just need to setup the domain to point to it. Alternatively you could host an instance easily if you have a VPS.

**Comment by IrosTheBeggar** [comment]
I'm trying to avoid managing more servers at the moment.  If you set it up, I'll point the domain at it

**Comment by aroundmyroom** [comment]
for whats worth: I do not care about any of the options..  I am on CET and if I want to ask something it is mostly not urgent to be fixed ;) mainly I make mistakes myself and rant to soon about something not working as expected ;) .. 

I use mStream every day at work where I use the randomness of the DJ function to listen to songs. With that and 141.000 songs in my library I listen daily to a lot of songs I never listened before ;)

**Comment by MaxLeiter** [comment]
@IrosTheBeggar do you want to hop onto IRC (or we can do over email) to discuss domain/ssl and such?

**Comment by IrosTheBeggar** [comment]
@MaxLeiter 

email me at paul.sori@gmail.com

**Comment by IrosTheBeggar** [comment]
I've got a matrix server running on matrix.mstream.io

**Comment by jugendhacker** [comment]
403 Forbidden...

**Comment by IrosTheBeggar** [comment]
Yea, it's still a work in progress. I've been able to connect with riot.  I've been having problems enablign guest accounts though

**Comment by MaxLeiter** [comment]
@IrosTheBeggar could you setup an IRC bridge in case some users (like me) want to use IRC?

**Comment by IrosTheBeggar** [comment]
@MaxLeiter I'm planning on it
