### ISSUE TITLE
permissions error on /save/db

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#154]
As the db resides now under mStream I have some issues but maybe it is all user error

git pull is used as user 'root' as things need to be compiled
mStream is running as normal user
When mStream is running as normal user, but mStream is in a folder not owned by the user we get errors. This is obvious, 

I think /save/db /save/log etc. should not be created by the git pull but by the user running mStream.
Otherwise you will get issues between the git pull and user running mStream.

I am not even sure if a sudo npm link etc will help or sudo git pull 

2018-11-19T07:43:35.489Z error: File scan error: error : Error: Error: EACCES: permission denied, open '/home/dennis/mStream/save/db/files.loki-v1.db~'

NB. I solved it manually, but I think other users could get in trouble when there is a difference between the user running mStream and the mStream binary.

**Comment by IrosTheBeggar** [comment]
The `EACCES: permission denied` error was due to to a bug from the v4 merge that has been fixed now.  I forgot to push the /save/logs and /save/db directory causing a fail to happen during write

mStream saves everything to its own directory by default because it's simple and works most of the time.  I also added a wizard to modify the config through a CLI program.  This should help guide new users to the right options to choose where to save their data if the standard config doesn't work for them

**Comment by aroundmyroom** [comment]
I pulled and the folders where there, but as I pull as root the folders are chmodded with root
I do not run mStream as root but as a user, as this user has no root rights it will get an access denied on those folders as mStream want to write its data as that user not as root

I will change this that all files in my folder are owned by that user, but I wonder if than things can be compiled correctly if necessary (I believe that sudo comes around the corner than)

**Comment by IrosTheBeggar** [comment]
Did you run git pull ad sudo? That's the only reason those folders would be under root

**Comment by aroundmyroom** [comment]
thats correct, but I will change that, as I had on my previous VM box issues with compiling node
now it resides on another VM and there I had no issues with node 10.x so I will chown this afternoon or later today everything
