### ISSUE TITLE
Federation

### ISSUE THREAD

**Issue by DblK** [IrosTheBeggar/mStream#189]
I just found out your project and I am impressed by the low consumption of memory which I was looking for in any solution.

I was wondering about the roadmap and if the federation can be added to it.
The idea behind this is to share a subset of the collection of music with another instance of mStream.

Any feedback about that?

**Comment by aroundmyroom** [comment]
What is the reason to have another instance of mStream?

**Comment by DblK** [comment]
To being able to share with friend's instance.
Let's say I have a running instance with some of my music. Without creating a user in my instance, I wish to be able to share all of it or a portion of my library to one of my friend.

Doing that he can still access to his music and have a portion of mine.

I hope I am clear about the use case.

**Comment by aroundmyroom** [comment]
interesting feature. but will cost bandwidth, difficult about opening ports to each another .. 
wonder if dev sees this as 'easy' to use ;)

**Comment by DblK** [comment]
It doesn't require to open new port, can be a specific route/api to sync across instance.
There are several protocol standard for federation.
Most of the work is already done, you should just "bother" about connecting the pipes ;)

**Comment by IrosTheBeggar** [comment]
@DblK 

File sharing/syncing is on my list. Idk if I would call it federation since it will not depend on a server.  What I have in mind is a file sync library that anyone can use to sync to a local computer. It could be used on its own or alongside mStream server. It could be used for creating remote backups as well.

On the server side everything is ready to go.  There’s already a share feature that shows this functionality in its basic form. A user can give access to a list of files to anyone with just a link.  What’s happening on the backend is the server is signing a custom JWT that gives access to a limited list of API endpoints and files.  

The missing part is a library that can run 24/7, store this JWT, and poll the server regularly for updates.  If something changes the library needs to be able to sync those changes to the local disk.

Hope that answers your question. If you want to help or just want some more info you can find me on discord: https://discord.gg/VDV6Gu

**Comment by IrosTheBeggar** [comment]
Just an update, I'm working on a federation feature that's backed by SyncThing.  I've been experimenting with SyncThing for a few weeks now and I'm really impressed with it.

**Comment by IrosTheBeggar** [comment]
@DblK  The latest commit has a federation implemented.

**Comment by uniquegch** [comment]
Hi There, when I click on "Enable Federation" I am getting the error message "Toggle failed" do I have to set something up / add in the config.json?
Thanks
