### ISSUE TITLE
Desktop clients?

### ISSUE THREAD

**Issue by aidenmadaffri** [IrosTheBeggar/mStream#198]
Any plans in the future for a desktop client (Windows/macOS/Linux). I love the application but it is hard for me to switch due to the last of a desktop client which I could control with my keyboard media controls.

**Comment by IrosTheBeggar** [comment]
I have been thinking about porting the webapp to a desktop app using electron, but there would need to be some serious modifications to get that done.  Otherwise I would need to work with an existing desktop application and add the mStream API to it.

Either way it's going to be a while, I've got a few other projects in the pipeline right now.  If any developers are interested, I could really use some help with a project like this.

**Comment by lukaswozniak** [comment]
Here is my attempt to make a desktop client: https://github.com/lukaswozniak/mstream-desktop-client
It's a webview (electron) with additional support for keyboard media controls, I kindly invite you to test and report bugs.

**Comment by IrosTheBeggar** [comment]
I just released a desktop app: https://github.com/IrosTheBeggar/mStream/releases/tag/v5.9.4
