### ISSUE TITLE
Why don't use relative-urls by default?

### ISSUE THREAD

**Issue by AlphaJack** [IrosTheBeggar/mStream#223]
The relative-urls branch makes it possible to access the app from an arbitrary location like https://example.com/mstream/, however it is outdated and misses the recent bugfixes and improvements introduced this month. Why don't merge it with the master?

**Comment by IrosTheBeggar** [comment]
Relative URLS breaks a  behavior that is expected by the server and frontend.

In it's current state the frontend and server are completely decoupled (if you poke around the source code, you'll notice a lot of features are decopupled as much as possible.  It's philosophy I strongly beleive in).  As long as the API is consistent, all other properties of the server and frontend can be changed without affecting each-other. The frontend takes extensive advantage of this feature by re-using code when possible.

The realtive-urls branch was made by another user and has several bugs that need to be addressed before being merged.

- The the media player relies on code that constructs absolute URLs.  You can see it works fine   in th main page, but breaks on the `/winamp` and `/shared/playlist` endpoints
- It breaks all custom fonts
- It breaks the `j/*` page that can be used to auto initiate a jukebox sessions
- It breaks some of my custom web-socket tests I'm using the see if multi-room audio is possible

If you can find a way to have both relative URLS and a decoupled system, feel free to submit a pull request fixing the above issues (I'm flexible on the web-socket thing, since it's not public yet).  You can also submit a pull request to merge the latest changes into the relative-urls branch. Otherwise I will be moving this to the project ice-box shortly.

**Comment by lukaswozniak** [comment]
I already have the branch rebased and fixed some of the issues. I will try to get it finished soon

**Comment by lukaswozniak** [comment]
After few hours of trying I have to admit that there is no easy way of fixing all of the issues. I was able to fix most of them but at the cost of code readability and possible future problems. I guess it's not worth doing after all.

**Comment by AlphaJack** [comment]
> I was able to fix most of them but at the cost of code readability and possible future problems. I guess it's not worth doing after all.

Great! I believe it's greatly worth it because people that selfhost on a subdomain like example.no-ip.com can still use the app from /mstream/ or another location, since they can't modify the no-ip.com DNS records or don't want to dedicate their server exclusively to mStream.
For these reasons I think it could even attract more users from other similar but slower (or more difficult to setup) services

**Comment by lukaswozniak** [comment]
### Relative urls approach

Having relative urls everywhere is currently impossible because we are serving the same static html content from mutliple locations, i.e. `/` and `/j/*`. This is solvable by instead of `/j/*`, have `/?jukebox=*`.  The project would need to live with this limitation.

Another thing is that the static html sites need to be aware from what endpoint they are served, so future changes of endpoints will cost additional html alignment.

Also the served javascript (can be limited only to parts shared between endpoints) would need to use additional global var which tells current location relative to root (i.e. "../../") and use it to build every url.

That was my approach and I already have most of the code ready, yet I see that this is not a satisfactory and clean solution.

### Serving mstream from `localhost:3000/mstream`

I belive we can achieve the same functionality by simply moving mstream from `localhost:3000/` to `localhost:3000/mstream`, and then serving mstream from your `example.no-ip.com/mstream` would come for free with a configuration like this:

```
location /mstream/ {
    proxy_pass http://localhost:3000/mstream/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
}
```

The drawback here is that current users nginx configuration would break, and to align it they would need to add redirection from `/` to `/mstream` to their nginx config. 

Also to not break current users who use mstream server directly we would need to implement redirection from `/` to `/mstream`, yet the previously generated shared playlists links will be invalid now (we could also redirect them to solve that).

As for me this is a more sane solution than the relative urls approach.


@IrosTheBeggar what do you think?

**Comment by AlphaJack** [comment]
If it may help, the [#350 issue](https://github.com/beancount/fava/issues/350) of [beancount/fava](https://github.com/beancount/fava/) has been solved by [introducing the "--prefix" flag](https://github.com/beancount/fava/commit/97bfc1649fbc91ece14b1474aeeef9fb6002f963) when launching the app:  

### Behaviour without prefix
Running `fava file.bc -p 5000` launches a web service on port 5000 and generate absolute urls like:  
```html
<link rel="stylesheet" href="/static/gen/app.css">
<script type="text/javascript" defer src="/static/gen/app.js"></script>
<a class="selected" data-key="g i" href="/example-beancount-file/income_statement/">Income Statement</a>
```
In this case the service is only available from http://host:5000

### Behaviour with prefix
Running `fava file.bc -p 5000 --prefix /fava` launches a web service on port 5000 and generate different absolute urls like:
```html
<link rel="stylesheet" href="/fava/static/gen/app.css">
<script type="text/javascript" defer src="/fava/static/gen/app.js"></script>
<a class="selected" data-key="g i" href="/fava/example-beancount-file/income_statement/">Income Statement</a>
```
In this case the service is available both from http://host:5000/fava and https://host/fava, through a reverse proxy.

### Nginx configuration
The reverse proxy configuration can be as simple as
```nginx
location /fava/   {
    proxy_pass http://127.0.0.1:5000/fava/;
}
```

---

This solution wouldn't break existing mStream configuration and should allow arbitrary location names, what do you think? @lukaswozniak @IrosTheBeggar

**Comment by AlphaJack** [comment]
Any update on this @IrosTheBeggar? [Shlink](https://github.com/shlinkio/shlink-web-client#serve-project-in-subpath) allows to generate custom static files (html, css, js) by specifying a property in `package.json` and by running `npm install`, could this be implemented for mStream? I'm stuck at 4.3 and I would like to update.

**Comment by d10n** [comment]
Fixed in #255 - please test

**Comment by AlphaJack** [comment]
@d10n any update on a possible merging?

**Comment by d10n** [comment]
@AlphaJack I think #255 is ready to merge, but I think only @IrosTheBeggar has permission to merge. If it helps, I created a `d10n-master` branch on my fork where I merged my PRs, and you could deploy from that in the meantime: https://github.com/d10n/mStream/tree/d10n-master

**Comment by buergi** [comment]
@d10n thanks great, I tried your branch, but I can't get it working... I'm constantly getting redirection loops, no matter what I try.
For example, I use the following line in config.json
```
"rootPath": "/dir/mstream",
```
and the following lines in my apache config
```
ProxyPass /dir/mstream http://127.0.0.1:45202/dir/mstream retry=0
ProxyPassReverse /dir/mstream http://127.0.0.1:45202/dir/mstream
```
Which leads to the following peculiar situation
```
$ curl https://server.com/dir/mstream;echo
Found. Redirecting to /dir/mstream/
$ curl https://server.com/dir/mstream/;echo
Found. Redirecting to /dir/mstream
$ curl https://server.com/dir/mstream/;echo
Found. Redirecting to /dir/mstream
$ curl https://server.com/dir/mstream/;echo
Found. Redirecting to /dir/mstream
$ curl https://server.com/dir/mstream/;echo
<!doctype html>
...
```
Some requests succeed some get redirected, no idea why.

I then added a / to the rootPath and to the second parameter of the two ProxyPath lines then I managed to get the mStream loading in the browser, however a lot of resources were missing as they are randomly redirected to /dir/mstream/
e.g.
```
$ curl https://server.com/dir/mstream/public/css/master.css
body, html {
  height: 100%; }
...
$ curl https://server.com/dir/mstream/public/css/master.css
Found. Redirecting to /dir/mstream/
```
Any ideas?

**Comment by buergi** [comment]
Had some difficulties with my apache, never mind. Thanks @d10 finally I can use mStream behind my apache proxy in a subdirectory 👍 Hope it will be merged soon into the official release.

**Comment by count00zero** [comment]
I would really love to see #255 merged. It is the only way I can run mstream in my setup. I love mstream, love it bleeding edge ... but without that fix I am currently running d10ns fork.

**Comment by AlphaJack** [comment]
> I would really love to see #255 merged. It is the only way I can run mstream in my setup. I love mstream, love it bleeding edge ... but without that fix I am currently running d10ns fork.

Same, I am using that fork also for the [AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mstream-git) package

**Comment by IrosTheBeggar** [comment]
I know it's been a while, but I'm finally getting around to this.

**Comment by IrosTheBeggar** [comment]
The latest commit works with relative URLs on the main page. Other pages still need to be converted.

Let me know if you run into any problems

**Comment by AlphaJack** [comment]
I did a quick test, some assets like fonts and playback icons are still being requested via absolute url
- left: http://127.0.0.1:3000/
- right: http://127.0.0.1:80/mstream/ pointing to http://127.0.0.1:3000/

![mstream-relative](https://user-images.githubusercontent.com/19962243/121753336-b3fc6300-cb01-11eb-9a9d-48fc0fa08aae.png)

Great work, also for the upcoming dark mode!

**Comment by buergi** [comment]
Great to see some progress here, still notice the same problems as @AlphaJack.
First I had some minor problems as I redirected

    <Location "/mstream">
      ProxyPass http://127.0.0.1:12345/ retry=0 timeout=5
      ProxyPassReverse http://127.0.0.1:12345/
    </Location>

Which caused ping to fail as the double slash in http://localhost:3000//api/v1/ping?false caused trouble.
Maybe in the future one could be more tolerant here. But after removing the trailing slash after the port it worked, to the extent as described by AlphaJack.
I temporarily and quite dirty fixed the some paths (see this patch [mstream-relative-patch.txt](https://github.com/IrosTheBeggar/mStream/files/6642787/mstream-relative-patch.txt)).
Then most things worked, the main thing which still is causing problems (meaning it doesn't work at all) is the admin interface. I changed URI in webapp/index.html so I could at least open the interface, but I'm immediately redirected to /login. Couldn't fix it so far.

But I'm still glad to see the progress and I'm really looking forward to future versions. Thanks a lot Iros.

**Comment by IrosTheBeggar** [comment]
@buergi thanks for the patch. I pushed some updates that cleanup the broken links on the main player page. I also pushed a patch that will forward you if you enter a URL with multiple slashes at the end

**Comment by IrosTheBeggar** [comment]
The main page and shared playlist pages should now both work with relative URLs. Let  me know if you see any problems

**Comment by IrosTheBeggar** [comment]
I just pushed a fix for the admin page

**Comment by IrosTheBeggar** [comment]
The latest releases has the fixes for the admin panel.

I'm closing this ticket. If you see any problems with relative URLs please open up a new ticket

**Comment by AlphaJack** [comment]
Thank you, many things seems to work now apart from the /login issue reported in #331.

Just a minor typo not worth opening a new issue, [this](https://github.com/IrosTheBeggar/mStream/blob/4cf737715c7c5043fc92bcc52d6844593e6f9090/webapp/admin/index.js#L1967) should be set to false to undo the admin lock
