### ISSUE TITLE
Error when uploading (drag and drop folder)

### ISSUE THREAD

**Issue by lukaswozniak** [IrosTheBeggar/mStream#243]
After drag and drop nothing happens. In console:
![image](https://user-images.githubusercontent.com/43893492/72908637-12227d80-3d36-11ea-8d30-d492e6257058.png)

**Comment by lukaswozniak** [comment]
I found cause of the problem. Seems that the folder I was uploading to had some non-Ascii characters in name. Currently the upload path was sent by a request header, which unfortunately cannot contain multibyte characters. I managed to get it fixed by sending the upload path by form data: #244

**Comment by IrosTheBeggar** [comment]
Good bug find.  Would like to get this fixed before release v5 soon.

I checked the pull request and had a question about it.  Do you know what happens if a 'file' event gets processed before the 'field' event is finished? 

```javascript
busboy.on('field', function(fieldname, dataLocation) {
  // ...
  busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
  });
});
```

 I am worried that since the `file` event is not set until the `field` event callback has been fully processed, that it is possible a `file` event could be missed and therefore not uploaded.   I need to research streams more to figure this out.

The reason the folder is stored in the headers is because the headers are guaranteed to be processed before any callbacks happen.  Maybe the folder names can be URL encoded before being put into the headers?

**Comment by lukaswozniak** [comment]
I have read that `multipart/form-data` request sends fields and files preserving their order. The dropzone library appends file data after emitting the `sending` event, so the order is good here and it should work always. I tested this pull request multiple times and every upload was successful.

**Comment by IrosTheBeggar** [comment]
Fixed on the latest commit
