### ISSUE TITLE
Playlist won't continue on Chrome 58.0.3029.83 for Android

### ISSUE THREAD

**Issue by erictb** [IrosTheBeggar/mStream#26]
Love the software, been looking for something like this for Android since StreamToMe isn't available for it. Firefox for Android works well, but Chrome has problems playing tracks. The first track in the playlist will play, but the next one won't. It will show up in the display, it will show the time remaining, but it just doesn't play. Not a game-breaker, but I thought you'd like to know.

**Comment by IrosTheBeggar** [comment]
Yea, chrome for android has some extra media restrictions that breaks the webapp.  Chrome for android requires the user to interact with the browser before playing media.  The idea is to prevent video ads from auto playing but it breaks the playlist because the user isn't interacting with the app most of the time.

I really need to find a mobile engineer to get an android app made

**Comment by IrosTheBeggar** [comment]
There is no clean way to get around this.  Instead, android users should use the mSteam android app.  

You can check out progress of the app here:

https://github.com/IrosTheBeggar/mstream-android-app

**Comment by IrosTheBeggar** [comment]
This has actually been fixed in the latest release.  Idk if it works on Safari, but it's working on chrome
