### ISSUE TITLE
Can't play music when sharing playlist

### ISSUE THREAD

**Issue by pinkfloydFR** [IrosTheBeggar/mStream#270]
Hi,

I am using "linuxserver/mstream:latest" docker image under ubuntu 18.04.

Behind apache2 proxy.

When sharing playlist, other user connect with no problem in mstream interface, they can see the playlist, but can't play it, ( progress bar not moving and no sound )

No log under my portainer, and nothing in the docker /var/log

Any idea ? Thanks !

EDIT ; pretty sure i need to tweak my reverse proxy, attachment
![mstream](https://user-images.githubusercontent.com/49475899/84994732-6c8c0280-b14b-11ea-8f01-2073555da136.png)

`
<VirtualHost *:1443>
        ServerName m.xxxxx.com
        ServerAlias ms.xxxxx.com

        ProxyPass / http://192.168.0.6:3080/
        ProxyPassReverse / http://192.168.0.6:3080/

        ErrorLog ${APACHE_LOG_DIR}/mstream-error.log
        CustomLog ${APACHE_LOG_DIR}/mstream-access.log combined

        Include ssl.conf
</VirtualHost>
`

**Comment by aroundmyroom** [comment]
that has probably nothing to do with your reverse proxy. I have mentioned this in #250 some months ago. Dev has to look up into this when he is able to. Corona shook up the world. Hope the best for everyone to get back to normal and back to normal jobs.

**Comment by jerrycan619** [comment]
Sometimes I get the same "errors" as you but they are not important as everything works with this "errors" (popper and butterchurn).

On Firefox it plays the shared playlist by clicking again on play/pause (only autoplay doesn't start).

On Chrome you are right, the songs are not starting to play.. however after waiting 2-5min on the shared page and then selecting another song of the playlist it works for me...?! please try this out and be sure to not select an other song or click play/pause within this 2-5min (otherwise you have to wait again) 

I think this is related to the "HTML5 Audio pool exhausted, returning potentially locked audio object." error. (discussed [here](https://github.com/goldfire/howler.js/issues/1110) )

(another bug is that currentSongText is not changing on shared playlist)

**Comment by pinkfloydFR** [comment]
> On Chrome you are right, the songs are not starting to play.. however after waiting 2-5min on the shared page and then selecting another song of the playlist it works for me...?! please try this out and be sure to not select an other song or click play/pause within this 2-5min (otherwise you have to wait again)



I confirm ! Well done for waiting.

**Comment by IrosTheBeggar** [comment]
These errors have been fixed on the new share page on v5-alpha.
