### ISSUE TITLE
[Question] IOS app or alternative

### ISSUE THREAD

**Issue by TUISTERa** [IrosTheBeggar/mStream#286]
Hello, is there any timeline for ios app, also is there any player alternative that i can use for ios, with mstream ? Thank you

**Comment by aroundmyroom** [comment]
with the latest release there is a way using the application as an PWA APP, this is fairly working fine, but there are some limitations on IOS.
Unfortunately mStream cannot play music when your screen goes into lock mode than it will stop. Very irritating cause I was playing music and streaming through bluetooth in the car and it stopped (I think there is nothing for this app what can be done, its the nature how Apple is handling PWA apps at this time.


but if you use the app and make sure you are not using the lock screen it will just play fine. Yes there are some little issues of features you should not use but if you know that it is working fine

What to do

load Mstream through the webbrowser to your location and login
press the middle button square with arrow pointing  (within the browser so not in the user interface) upwards and tell it to put it on the homescreen (square with + sign)
this is the way to add PWA apps on your phone / ipad

**Comment by IrosTheBeggar** [comment]
I really want to do an iOS app. And there's significant progress towards it actually.  The current app is built with Flutter which can compile into iOS and Android.  The main thing preventing me is money:

- Buying a iOS developer license is a yearly fee
- I need Mac hardware to develop iOS software.  I don't have any mac computers . I looked into buying an old imac on the cheap, but it turns out i would need to buy a modern mac to develop for iOS.  The old macs can't run the latest version of Swift for some reason.

I have to give google credit here.  Developing for Android has cost me a total of $20 for a lifetime developer fee. And the software + emulators run on any OS.

**Comment by bmcgonag** [comment]
Not sure if this will help, but here's a link about building iOS version without a Mac.
https://blog.codemagic.io/how-to-develop-and-distribute-ios-apps-without-mac-with-flutter-codemagic/

**Comment by x2ih** [comment]
I have a solution. Via Safari on iPhone, open your mStream server or demo.mstream.io, play a music or playlist then open a new tab on safari, then you can close screen or use other apps ;-)


See photos:

![4044F9CA-F658-448F-A1EF-70381416F07C](https://user-images.githubusercontent.com/75285768/144525029-7833889e-65ba-4418-9f66-f61e0b99c5c7.jpeg)
![93A1E6EB-ACAA-4F24-9B79-60B9157595EB](https://user-images.githubusercontent.com/75285768/144525031-470be589-e5ea-4ba6-b704-c072a6e66a5b.jpeg)

**Comment by IrosTheBeggar** [comment]
There's an iOS app that's being worked on by another dev. You can ask permission to be a beta tester in the Discord server

**Comment by IrosTheBeggar** [comment]
There is now an iOS App!

https://apps.apple.com/us/app/mstream-player/id1605378892
