### ISSUE TITLE
Folder and Vpaths cannot contain spaces

### ISSUE THREAD

**Issue by aroundmyroom** [IrosTheBeggar/mStream#288]
When using spaces in a folder and vpath files cannot be found when trying to access  these folder(s) it's access denied

"folders": {
    "Genre-A-B": { "root": "/media/music/rock"},
    "Genre C D": { "root": "/media/music/blues"}

"vpaths": ["Genre-A-B", "Gengre C D"],

Genre-A-B with its contents can be accessed but Genre C D not. 'Call Failed'

**Comment by IrosTheBeggar** [comment]
This is due to how the server side of mstream works.  vPaths get used in the URLs of music files.  URL's don't work well with special characters (including whitespace).

I'm working on some new features that will allow you to manage folders and users with a new UI.  This way the UI will prevent you from using special characters

**Comment by IrosTheBeggar** [comment]
I added an admin panel to the latest commit.  It's still really early in development, but it shows a complete example of updating the config via the UI

**Comment by aroundmyroom** [comment]
running 5.0-alpha now ;)

**Comment by IrosTheBeggar** [comment]
The admin UI takes care of this now
