### ISSUE TITLE
Disabled automatic scanning

### ISSUE THREAD

**Issue by IrosTheBeggar** [IrosTheBeggar/mStream#296]
Requested by a user on the Discord server

**Comment by yurmax** [comment]
Tnx for creating this theme. It was me. I asked to disable rescan at startup.
And one more question.
Is it possible to make a version without a database, for old CPUs?
I don't know, for example, to read tags directly, not from the database.
Because it takes too long to create even the first database file.
On my Dual-Core CPU E5400, 2.70GHz, the base for 15k files takes almost two hours.

**Comment by aroundmyroom** [comment]
if mStream can work with a disabled scan you can just play the music from folders. The only issue you probably have is that some elements needs the database (ie. playlist etc.) so maybe Paul can elaborate if that would be possible

**Comment by IrosTheBeggar** [comment]
You can disable automatic scans by setting the `Scan Interval` to 0 in the admin page (under the database tab). You can also do this by editing your json config file and setting `scanInterval` to 0.

Your database will still be initialized and you will still be able to run a scan manually.

**Comment by IrosTheBeggar** [comment]
@yurmax 

Closing this ticket and mentioning you to make sure you saw this
