### ISSUE TITLE
Fail to install due to bcrypt error

### ISSUE THREAD

**Issue by kuriot** [IrosTheBeggar/mStream#31]
Hello.

mStream fails to install through npm (in docker too) with this error:

```
npm ERR! Linux 4.4.0-78-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "mstream"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! bcrypt@1.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@1.0.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-05-31T19_40_42_507Z-debug.log
```

**Comment by IrosTheBeggar** [comment]
Have you tried installing mStream via cloning the repository and running npm install?  For some reason that method magically fixes the bcrypt error for some people

**Comment by kuriot** [comment]
Yes, that way it works! Awesome streaming service (all the evening I'm trying different services and this one is the best by far for streaming FLACs).

Anyway, maybe I'm a little bit stupid but in album or artist view how do I go to the parent folder?

![](http://i.imgur.com/FrHC5gi.png)

**Comment by IrosTheBeggar** [comment]
Glad you like it.  Flac support has always been a priority feature when making mStream.  Lack of good flac support is actually part of the reason I started the project.

And you're not stupid. I ripped out a bunch of controls a while back  during a rewrite and forgot to add that back in.  I usually listen to an album at a time, so it slipped past my radar.  I'll readd that shortly

**Comment by kuriot** [comment]
Thanks for help. :) 

As for bcrypt error. When I git cloned and made `npm install` at one moment it gave the same error and then compiled it from local subdirectory. Maybe bcrypt sources should be added to Docker script too?..

Anyway, I think this ticket is done and may be closed.

**Comment by IrosTheBeggar** [comment]
I opened up an issue on the bscrypt repository:
https://github.com/kelektiv/node.bcrypt.js/issues/509

**Comment by eresonance** [comment]
Note that I had this same issue, but an update of nodejs fixed it. Not entirely sure why.

```
$ node --version
v6.11.0
```

**Comment by IrosTheBeggar** [comment]
It looks like when using `npm instal -g mstream` node-gyp searches for pre-compiled versions of bcrypt and fails when it doesn't find any.

However when installing it via cloning, node-gyp compiles the code from scratch instead of failing

**Comment by IrosTheBeggar** [comment]
I updated the docs  to make the git installation method the main method.  This way no one runs into this error.

There's not much more I can do since this is an error with bcrypts npm repository

**Comment by shahabshahidi** [comment]
I also have this error when installing bcrypt

npm ERR! Code 1
npm ERR! path C:\Users\ttl\Desktop\testnpm\node_modules\bcrypt
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build -- module=C:\Users\ttl\Desktop\testnpm\node_modules\bcrypt\lib\binding\napi-v3\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\ttl\Desktop\testnpm\node_modules\ bcrypt\lib\binding\napi-v3 --napi_version=9 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
npm ERR! node-pre-gyp info using node@20.12.1 | win32 | x64
npm ERR! node-pre-gyp info check checked for "C:\Users\ttl\Desktop\testnpm\node_modules\bcrypt\lib\binding\napi-v3\bcrypt_lib.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.1.1/bcrypt_lib-v5.1.1-napi-v3-win32-x64-unknown.tar.gz
npm ERR! node-pre-gyp ERR! install request to https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.1.1/bcrypt_lib-v5.1.1-napi-v3-win32-x64-unknown.tar.gz failed, reason: Unable to verify the first certificate
.
.
.
I don't know what the problem is!!
