### ISSUE TITLE
Emulate Subsonic API

### ISSUE THREAD

**Issue by IrosTheBeggar** [IrosTheBeggar/mStream#62]
Building mobile apps sucks.  Might as well leverage what's out there already

**Comment by madman2021** [comment]
+1

**Comment by aroundmyroom** [comment]
+4 (hahah) .. I am trying to move away from subsonic, but the apps with subsonic work, so using that API yes... (my db is around 4TB of music) so I need something quick. Mstream seems to be .. just did a quick install on debian, but will setup a new vm after the F1 training today ;)

**Comment by IrosTheBeggar** [comment]
Development on a flutter based mobile app has started: https://github.com/IrosTheBeggar/mstream-flutter

**Comment by fidelix** [comment]
I appreciate the effort, but there are a dozen mobile apps that are stable and filled with features that are compatible with the subsonic API - some of them open source and very decent.

Not having a good mobile app is going to be a big blocker for a lot of people interested in using mStream. It is for me.

**Comment by HubKing** [comment]
Sorry for nagging about a free programme, but the iOS client needs more work. First, it does not support iPad. At first, when I searched the Store, I could not even find it, because by default only the apps that support iPad appear in the result. The mStream website had no link to the iOS app, so I had to search Google.

When I installed it, its window was small like an iPhone. Then, connection to server failed, when the Android client succeeded. It only worked after I enabled a user name and password. That is, the iOS app seems to have a bug that it cannot connect if the user ID/password has not been enabled. And even then, the UI looked so barren. It did not even show the album art. Also, it ignored the system theme (dark) and showed an all-white UI.

Yeah, I know, developing an iOS app takes efforts and money (damn greedy Apple charge $100 annual fee). Then, wouldn't it be better, like the person above said, just to support a common API and use existing clients?

**Comment by aroundmyroom** [comment]
@HubKing mStream aka Paul did not build the iOS aka iPhone app, a user of mStream did. mStream itself has an API and everyone can build an app if they want. Its known that a lot of things can be added. But also for this developer: he is doing it in his free time. Due to covid a lot of things has happened personally and professionally for a lot of people. So the most important part is to be able to survive, development of this free tool is a nice-to-have.

I have used a lot of existing clients be able to talk with subsonic api. Even the best client I used was/is abandoned. Not to mention subsonic itself. 

the developer of this app is on Discord, so you can get in touch with him ..
