### ISSUE TITLE
[Feature Request] Automatic Transcoding

### ISSUE THREAD

**Issue by ehea617** [IrosTheBeggar/mStream#67]
Lossless music is big and takes up a lot of data when streaming to a mobile device. Automatic transcoding options would allow me to stream MP3 to mobile devices without having to convert all of my lossless music to MP3 first.

Another nice side effect of implementing this would be allowing playback of files that are unsupported in certain web browsers.

**Comment by IrosTheBeggar** [comment]
I'm looking into implementing trans-coding with Sox: http://sox.sourceforge.net/

**Comment by IrosTheBeggar** [comment]
Working on implementing this now with ffmpeg

**Comment by resuser** [comment]
Adding my support for this feature. mStream seems to be the simple media server solution I want, but the lack of transcoding is a showstopper for me. Much of my media is flac, and I can't have that streaming over my data plan.
Thanks for working to make this happen!

**Comment by jugendhacker** [comment]
@IrosTheBeggar are you still working on it? I want to try to do this myself but not sure if your already have code for it....

**Comment by IrosTheBeggar** [comment]
There's some working code in the `/modules/ffmpeg.js file`.  

The problem is it causes some problems with the webapp player (seek is broken and sometimes the next song fails to queue). Also the UI is missing controls to enable/disable it.

If you want to do some quick and dirty testing, you can edit `api2.js` and end edit line 170 and replace  `/media/` with `/transcode/`.  That will force the webapp to use the transcode endpoint

You will also need to use npm  to install `ffbinaries` and `fluent-ffmpeg`.

And you will need to edit the code in `mstream.js` to enable the ffmpeg file:

 `require("./modules/ffmpeg.js").setup(mstream, program);`

**Comment by IrosTheBeggar** [comment]
This has been added!  However it's still an experimental feature and needs some work. Issues with transcoding will be tracked here: https://github.com/IrosTheBeggar/mStream/issues/213
