### ISSUE TITLE
Add ListenBrainz scrobbling

### ISSUE THREAD

**Issue by gorgobacka** [IrosTheBeggar/mStream#85]
as an open source alternative to Last.fm

https://listenbrainz.org/

**Comment by gorgobacka** [comment]
It's sad to see this feature request closed.

**Comment by IrosTheBeggar** [comment]
@gorgobacka Sorry, I should have left an explanation.  I looked into this and it actually is not possible to implement this due to a limitation of the ListenBrainz API.

At the bottom of the API docs there's a section on rate limiting: https://listenbrainz.readthedocs.io/en/production/dev/api.html#rate-limiting

In this case all mStream servers are seen as a single client by ListenBrainz.  mStream servers do not talk to eachother, so there's no way to assure that each server would obey the rate limit.  Users can be locked out and unable to talk to ListenBrainz because one mStream server is hogging the rate limit.

So until there is a way to register each unique mStream server as a ListenBrainz client, I don't see a path forward for this.   I'm open to  ideas though.

**Comment by ahstro** [comment]
Why would all mStream servers be seen a s a single client? Wouldn't a user simply add a ListenBrainz API token to their config? (I only skimmed the LB docs, so sorry if I missed something obvious)
